# Generated by Django 6.0.5 on 2026-06-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leave_email_alter_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(default='Casual Leave', max_length=100),
        ),
    ]
