# Generated by Django 6.0.6 on 2026-06-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_leave_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='duration',
            field=models.CharField(choices=[('full', 'Full Day'), ('half', 'Half Day')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='leave',
            name='half_day_session',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=20, null=True),
        ),
    ]
