# Generated by Django 6.0.6 on 2026-06-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_leave_duration_leave_half_day_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='total_days',
            field=models.FloatField(default=0),
        ),
    ]
