# Generated by Django 6.0.6 on 2026-06-19 05:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0006_balnaceleave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BalnaceLeave',
            new_name='LeaveBalance',
        ),
    ]
