# Generated by Django 6.0.6 on 2026-06-19 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0007_rename_balnaceleave_leavebalance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavebalance',
            old_name='remaining_leaves',
            new_name='remaining_leave',
        ),
    ]
